EVENT_STREAM = "COPY_TRADE_EVENTS"

EXCHANGE_TRADE_EVENT_NORMALIZED = "exchange.trade_event.normalized"
EXCHANGE_ORDER_UPDATE_NORMALIZED = "exchange.order_update.normalized"

COPY_EXECUTION_REQUESTED = "copy.execution.requested"
COPY_EXECUTION_ACCEPTED = "copy.execution.accepted"
COPY_EXECUTION_REJECTED = "copy.execution.rejected"
COPY_EXECUTION_FILLED = "copy.execution.filled"
COPY_EXECUTION_FAILED = "copy.execution.failed"
COPY_EXECUTION_RESULT_SUBJECTS = (
    COPY_EXECUTION_ACCEPTED,
    COPY_EXECUTION_REJECTED,
    COPY_EXECUTION_FILLED,
    COPY_EXECUTION_FAILED,
)

BILLING_ORDER_CREATED = "billing.order.created"
BILLING_PAYMENT_VERIFIED = "billing.payment.verified"

NOTIFICATION_REQUESTED = "notification.requested"
AUDIT_EVENT_CREATED = "audit.event.created"
DEAD_LETTER_EVENT_CREATED = "system.dead_letter.created"

ALL_EVENT_SUBJECTS = (
    EXCHANGE_TRADE_EVENT_NORMALIZED,
    EXCHANGE_ORDER_UPDATE_NORMALIZED,
    COPY_EXECUTION_REQUESTED,
    COPY_EXECUTION_ACCEPTED,
    COPY_EXECUTION_REJECTED,
    COPY_EXECUTION_FILLED,
    COPY_EXECUTION_FAILED,
    BILLING_ORDER_CREATED,
    BILLING_PAYMENT_VERIFIED,
    NOTIFICATION_REQUESTED,
    AUDIT_EVENT_CREATED,
    DEAD_LETTER_EVENT_CREATED,
)

COPY_ENGINE_NORMALIZED_TRADES_DURABLE = "copy_engine_normalized_trades"
COPY_ENGINE_EXECUTION_ACCEPTED_DURABLE = "copy_engine_execution_accepted"
COPY_ENGINE_EXECUTION_REJECTED_DURABLE = "copy_engine_execution_rejected"
COPY_ENGINE_EXECUTION_FILLED_DURABLE = "copy_engine_execution_filled"
COPY_ENGINE_EXECUTION_FAILED_DURABLE = "copy_engine_execution_failed"
COPY_ENGINE_EXECUTION_RESULT_DURABLES = {
    COPY_EXECUTION_ACCEPTED: COPY_ENGINE_EXECUTION_ACCEPTED_DURABLE,
    COPY_EXECUTION_REJECTED: COPY_ENGINE_EXECUTION_REJECTED_DURABLE,
    COPY_EXECUTION_FILLED: COPY_ENGINE_EXECUTION_FILLED_DURABLE,
    COPY_EXECUTION_FAILED: COPY_ENGINE_EXECUTION_FAILED_DURABLE,
}
